name: Deploy to Production Server

on:
  workflow_dispatch:   # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key (reuse test key for prod)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_TEST }}" > ~/.ssh/prodserver.pem
          chmod 600 ~/.ssh/prodserver.pem

      - name: Deploy to EC2 Production Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem ubuntu@${{ secrets.EC2_PROD_IP }} "
            cd ~/ci-cd-pipeline-demo &&
            git pull origin main &&
            chmod +x ~/deploy.sh &&
            bash ~/deploy.sh
          "





