name: Deploy to Test Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write SSH key from secret
        run: |
          mkdir -p ~/.ssh
          umask 077
          cat > ~/.ssh/testserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_TEST }}
          EOF
          chmod 600 ~/.ssh/testserver.pem

      - name: Test SSH connectivity (verbose)
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/testserver.pem ubuntu@${{ secrets.EC2_TEST_IP }} "echo connected OK"

      - name: Deploy to EC2 Test Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/testserver.pem ubuntu@${{ secrets.EC2_TEST_IP }} "bash ~/deploy.sh"



