name: Deploy to Production

on:
  # Manual trigger from Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to deploy"
        required: false
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout (metadata only)
        uses: actions/checkout@v4

      - name: Write SSH key from secret (newline-safe)
        run: |
          mkdir -p ~/.ssh
          umask 077
          cat > ~/.ssh/prodserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_PROD }}
          EOF
          chmod 600 ~/.ssh/prodserver.pem

      - name: Determine ref to deploy
        id: pickref
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "ref=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref || 'main' }}" >> $GITHUB_OUTPUT
          fi
          echo "Deploying ref: $(cat $GITHUB_OUTPUT)"

      - name: Test SSH connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem \
            ubuntu@${{ secrets.EC2_PROD_IP }} "echo '✅ SSH to prod works'"

      - name: Deploy to EC2 Production
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem \
            ubuntu@${{ secrets.EC2_PROD_IP }} "bash ~/deploy.sh"


