name: Deploy to Test Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          umask 077
          # Use the correct secret name for the test server key
          cat > ~/.ssh/testserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_TEST }}
          EOF
          chmod 600 ~/.ssh/testserver.pem

      - name: Copy Files to EC2 Test Server
        run: |
          # Use SCP to copy the entire repository to the server
          # -o StrictHostKeyChecking=no and -o UserKnownHostsFile=/dev/null fix the host key error
          # -r copies the directory recursively
          # . is the source (local repo root)
          # ubuntu@...:~/ci-cd-pipeline-demo is the destination path on the server
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r \
              -i ~/.ssh/testserver.pem \
              . ubuntu@${{ secrets.EC2_TEST_IP }}:~/ci-cd-pipeline-demo
          
          # Ensure the deploy script is executable on the server
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/testserver.pem \
              ubuntu@${{ secrets.EC2_TEST_IP }} "chmod +x ~/ci-cd-pipeline-demo/deploy.sh"


      - name: Execute Deployment Script on Test Server
        run: |
          echo "Executing deployment script on ${{ secrets.EC2_TEST_IP }}"
          # Execute the deploy.sh script that was just copied
          # Install dependencies and run the app
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/testserver.pem \
              ubuntu@${{ secrets.EC2_TEST_IP }} "~/ci-cd-pipeline-demo/deploy.sh"