name: Deploy to Test Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          umask 077
          # Use the correct secret name for the test server key
          cat > ~/.ssh/testserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_TEST }}
          EOF
          chmod 600 ~/.ssh/testserver.pem

      - name: Test SSH connectivity (with host check disabled)
        run: |
          echo "Testing SSH to ${{ secrets.EC2_TEST_IP }}"
          # --- CORRECTED SSH COMMAND HERE ---
          ssh -vvv -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/testserver.pem ubuntu@${{ secrets.EC2_TEST_IP }} "echo Connected OK"
          # ----------------------------------

      - name: Deploy to EC2 Test Server (with host check disabled)
        run: |
          # --- CORRECTED SSH COMMAND HERE ---
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/testserver.pem ubuntu@${{ secrets.EC2_TEST_IP }} "bash ~/deploy.sh"
          # ----------------------------------
