name: Deploy to Test Server

on:
  push:
    branches:
      - main    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Local Dependencies for CI Checks
        run: |
          echo "Installing dependencies required for any local CI checks..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          umask 077
          cat > ~/.ssh/testserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_TEST }}
          EOF
          chmod 600 ~/.ssh/testserver.pem

      # Fix permissions before copying files
      - name: Pre-Deployment Cleanup (Fix Permissions)
        run: |
          echo "Fixing file ownership on target directory..."
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/testserver.pem \
              ubuntu@${{ secrets.EC2_TEST_IP }} "sudo chown -R ubuntu:ubuntu ~/ci-cd-pipeline-demo || true"
          # '|| true' handles the case where the directory might not exist yet.
          
      - name: Copy Files to EC2 Test Server
        run: |
          # Use SCP to copy the entire repository to the server
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r \
              -i ~/.ssh/testserver.pem \
              . ubuntu@${{ secrets.EC2_TEST_IP }}:~/ci-cd-pipeline-demo
          
          # Ensure the deploy script is executable on the server
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/testserver.pem \
              ubuntu@${{ secrets.EC2_TEST_IP }} "chmod +x ~/ci-cd-pipeline-demo/deploy.sh"


      - name: Execute Deployment Script on Test Server
        run: |
          echo "Executing deployment script on ${{ secrets.EC2_TEST_IP }}"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              -i ~/.ssh/testserver.pem \
              ubuntu@${{ secrets.EC2_TEST_IP }} "~/ci-cd-pipeline-demo/deploy.sh"
