name: Deploy to Production

on:
  # Run manually from the Actions tab
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to deploy"
        required: false
        default: "main"
  # Uncomment if you also want release-based deploys
  # release:
  #   types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # optional: protect with required reviewers in Settings → Environments

    steps:
      - name: Checkout (metadata only)
        uses: actions/checkout@v4

      - name: Write SSH key from secret (newline-safe)
        run: |
          mkdir -p ~/.ssh
          umask 077
          cat > ~/.ssh/prodserver.pem << 'EOF'
          ${{ secrets.EC2_SSH_KEY_PROD }}
          EOF
          chmod 600 ~/.ssh/prodserver.pem

      - name: Determine ref to deploy
        id: pickref
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "ref=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref || 'main' }}" >> $GITHUB_OUTPUT
          fi
          echo "Deploying ref: $(cat $GITHUB_OUTPUT)"

      - name: Test SSH connectivity (verbose)
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem \
            ubuntu@${{ secrets.EC2_PROD_IP }} "echo connected OK"

      - name: Deploy to EC2 Production (uses ~/deploy.sh on server)
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem \
            ubuntu@${{ secrets.EC2_PROD_IP }} "bash ~/deploy.sh"

      # ── Alternative: deploy an exact ref/tag instead of what deploy.sh pulls ──
      # - name: Deploy exact ref to EC2 Production
      #   env:
      #     DEPLOY_REF: ${{ steps.pickref.outputs.ref }}
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem ubuntu@${{ secrets.EC2_PROD_IP }} bash -lc '
      #       set -e
      #       APP_DIR="$HOME/ci-cd-pipeline-demo"
      #       if [ ! -d "$APP_DIR" ]; then
      #         git clone https://github.com/abrar914/ci-cd-pipeline-demo.git "$APP_DIR"
      #       fi
      #       cd "$APP_DIR"
      #       git fetch --all --tags
      #       git checkout -f "${DEPLOY_REF:-main}"
      #       python3 -m pip install --upgrade pip
      #       pip3 install -r requirements.txt
      #       pkill -f app.py || true
      #       nohup python3 app.py > app.log 2>&1 &
      #       sleep 1
      #       curl -sI http://127.0.0.1:8000 | head -n1 || true
      #     '

