name: Deploy to Test Server

on:
  push:
    branches:
      - main   # runs only when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_TEST }}" > ~/.ssh/testserver.pem
          chmod 600 ~/.ssh/testserver.pem

      - name: Deploy to EC2 Test Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/testserver.pem ubuntu@${{ secrets.EC2_TEST_IP }} "bash ~/deploy.sh"


