name: Deploy to Production Server

on:
  workflow_dispatch:   # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key (reuse test key for prod)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY_TEST }}" > ~/.ssh/prodserver.pem
          chmod 600 ~/.ssh/prodserver.pem

      - name: Deploy to EC2 Production Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/prodserver.pem ubuntu@${{ secrets.EC2_PROD_IP }} "
            # Ensure app folder exists
            cd ~/ci-cd-pipeline-demo || git clone https://github.com/abrar914/ci-cd-pipeline-demo.git ~/ci-cd-pipeline-demo
            cd ~/ci-cd-pipeline-demo

            # Pull latest code
            git pull origin main

            # Install/upgrade dependencies
            python3 -m pip install --upgrade pip --user
            pip3 install -r requirements.txt --user

            # Restart app
            pkill -f app.py || true
            nohup python3 app.py > app.log 2>&1 &

            # Quick health check
            sleep 2
            curl -sI http://127.0.0.1:8000 | head -n1 || true
          "







